### ISSUE TITLE
Default sort_by value

### ISSUE THREAD

**Issue by mbajur** [RStankov/SearchObject#11]
Hello, first of all - thanks for this lovely plugin, i hope you have not abandoned it 🤞 

I was wondering - is that possible to set a default value for `sort_by` option? If that's important - i would love to have such option in graphql plugin.

Thanks!

---

edit: it actually turned out sorting is probably not possible by graphql plugin as including both is not making `sort_by` method adding `sort` argument to the graphql connection - am i doing something wrong in here?

**Comment by RStankov** [comment]
Hey, 

Thanks for the kind words. 🙌

I'm still working on SearchObject. I'll be doing an update this month improving the GraphQL plugin.

`sort_by` have a default option:

https://github.com/RStankov/SearchObject/blob/master/lib/search_object/plugin/sorting.rb#L43-L46

In my projects, I haven't used this plugin for a long time.
