### ISSUE TITLE
Combining graphql with sorting seems not possible?

### ISSUE THREAD

**Issue by Sebbb** [RStankov/SearchObject#13]
Hello,

I try to use the GraphQL module together with the sorting module.

filtering works fine, but as soon as I add

`include SearchObject.module(:sorting, :graphql)
`

it stops working. Depending on if I first specify sorting I get
`"Field 'allTasks' doesn't accept argument 'sort'"`

or if I load the GraphQL module first:
`error:     "message": "GraphQL type has to passed as :type to 'sort' option",`

How is it possible to use both functions? Unfortunately there is no documentation/example that fits..

Thanks
Sebastian

**Comment by RStankov** [comment]
Hey, @Sebbb my suggestion is to not use `sorting` with `graphql`.

Since the biggest advantage of `sorting` are `#sort?`, `#reverted_sort_direction`, `#sort_direction_for` and `sort_params_for`. In GraphQL settings you don't need those. You can just use [enum](https://github.com/RStankov/SearchObjectGraphQL#enums-support):

```
class PostSearch
  include SearchObject.module(:graphql)

  SortEnum = GraphQL::EnumType.define do
    name 'PostSort'

    value 'RECENT'
    value 'VIEWS'
    value 'COMMENTS'
  end

  option :sort, type: SortEnum, default: 'RECENT'

  def apply_sort_with_recent(scope)
    scope.order 'created_at DESC'
  end

  def apply_sort_with_views(scope)
    scope.order 'views_count DESC'
  end

  def apply_sort_with_comments(scope)
    scope.order 'comments_count DESC'
  end
end
```

**Comment by Sebbb** [comment]
Hey,

thanks for the information. However, maybe it makes sense to adjust the documentation and state that the graphql-module is basically exclusive, it does not make sense to include any other module?

Cheers,
Sebastian

**Comment by begin29** [comment]
hey @RStankov, 
your `options :order` example is great , but how to get reverse order? 

Some second argument should be passed into handler but can't figure out how to do that.
