### ISSUE TITLE
Allow more flexible use of enum

### ISSUE THREAD

**Issue by hschne** [RStankov/SearchObject#17]
First of all: Thanks for writing this, SearchObject and SearchObjectGraphQL have been very helpful for our GraphQL API! 

However, in using it with enums, we have found the behavior of the enum type with GraphQL somewhat restrictive. Assuming we have some enum and search object: 

```ruby
class MyEnum < BaseEnum
      value('OPEN', 'Open', value: :open)
      value('COMPLETE', 'Complete', value: :complete)
end

class MySearch < BaseResolver
    include SearchObject.module(:graphql)

   ...

  option(:status, type: MyEnum)

   def apply_status_with_open(scope)
    scope.open
  end
  def apply_status_with_complete(scope)
    scope.open
  end
  ...
```

Now, let's say our base object does not have the required scopes. There is no way to define some custom query while still taking advantage of GraphQL enums - I would have to resort to string types of the argument. But something like this would be nice:

```ruby
option(:status, type: MyEnum) do |scope, value|
  MyModel.where(status: MyModel::STATUS[value]
end  
```

This can be archived by modifying the enum plugin the tiniest bit:

```ruby
module SearchObject
  module Plugin
    module Enum
      module ClassMethods
         def option(name, options = nil, &block)
            return super unless options.is_a?(Hash) && options[:enum]

           # Remove raises if block or with is passed and add those
           handler = options[:with] || block || Handler.build(name, options[:enum])

           super(name, options, &handler)
       end
    end
  end
end
```

I'm not sure why enums where tied to `apply` methods in the first place, so I might overlook something, but allowing a block/with handler for enums as well provides a lot more flexibility and does not add additional costs, right?

I can open a PR if you would accept this change :smile:

**Comment by RStankov** [comment]
Great idea. I'll be happy a PR merging this :)

**Comment by RStankov** [comment]
Resolved by https://github.com/RStankov/SearchObject/pull/18 🙌
