### ISSUE TITLE
Elasticsearch support

### ISSUE THREAD

**Issue by denissellu** [RStankov/SearchObject#19]
Hi, 

Great gem, we've build something similar to it internally that works just with Elasticsearch

Just wondering if you have any plans to extend it / add a plugin for Elasticsearch?

Maybe I could submit a PR?

cheers

**Comment by RStankov** [comment]
Hey, 

Elasticsearch plugin sounds like great idea.Adding elastic support should be quite easy. I suggest having a separate plugin gem like the [GraphQL](https://github.com/RStankov/SearchObjectGraphQL) plugin.

The gem design is so it doesn't depend on anything external and can connect to pretty much everything.

**Comment by denissellu** [comment]
thats makes sense, i'll give it a try

**Comment by RStankov** [comment]
Great, ping me if you need any help :)
