### ISSUE TITLE
Unexpected results on joins with where

### ISSUE THREAD

**Issue by jakemumu** [RStankov/SearchObject#20]
Hey -- thanks for this gem I'm giving it a shot. 

I've got a query I ran in console and then added to my scopes but it's returning me something. I have a taggings table, the scope is like: 

```
scope.joins(:taggings).where(taggings: { tag: tag })
```

I would expect this to return objects in the scope which contain the given tag, but instead the search result is returning the tag to me. -- apologies if this is something simple, I'm no expert on queries.

**Comment by RStankov** [comment]
Hey,

* What is the full search object class code?
* What does this return ? what is the expected result?
