### ISSUE TITLE
Keeping state on back event

### ISSUE THREAD

**Issue by luxxi** [RStankov/SearchObject#3]

**Comment by RStankov** [comment]
Hi, can you elaborate what you mean by "Keeping state on back event" ?

**Comment by luxxi** [comment]
Sorry something weird happen when i saved the post and some how i lost the content.

If you look in example app. When you select the author in dropdown it gets selected and content change on site which is what user expect. Problem is if you click browser back button the content change but author stayed selected in dropdown. This is bad for ux because you have all content displayed and selected author.
<img width="1342" alt="screen shot 2015-09-13 at 13 34 42" src="https://cloud.githubusercontent.com/assets/1362438/9899648/84d78340-5c5b-11e5-8896-0da680f730e3.png">

**UPDATE**
I found this is browser job to keep previous state and on back event display the forms in case the user accidentally clicked on something else. Is there any work around that?

**Comment by RStankov** [comment]
Unfortunately this is a browser behavior, not related to `SearchObject`. I'll will try to fix it in the example.
